version: '3.8'

services:
  database:
    image: 'postgres:17.6'
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - app-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/

  storybook-be:
    build:
      context: ./storybook-backend
      dockerfile: Dockerfile
    container_name: storybook-be
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres?currentSchema=public
    networks:
      - app-network

  storybook-fe:
    build:
      context: ./storybook-frontend
      dockerfile: Dockerfile
    container_name: storybook-fe
    ports:
      - "80:80"
    depends_on:
      - storybook-be
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
